// 診断専用：WebKit で aube #1645 を実行し、手順の区切りの時刻を記録する。終了後もページを閉じずに観察する。
import { spawn } from 'node:child_process';
import { writeFileSync, appendFileSync, rmSync } from 'node:fs';
import { webkit, chromium } from '@playwright/test';
const which = process.argv[2] ?? 'webkit';
const dir = 'test-results/wkcpu';
const samples = `${dir}/${which}-cpu.txt`, stop = `${dir}/stop`, marks = `${dir}/${which}-marks.txt`;
rmSync(samples, { force: true }); rmSync(stop, { force: true }); writeFileSync(marks, '');
const mark = (s) => appendFileSync(marks, `${Date.now()} ${s}\n`);
const server = spawn(process.execPath, ['scripts/serve.mjs', '--port', '8792'], { stdio: ['ignore', 'pipe', 'inherit'] });
await new Promise((r) => server.stdout.on('data', (d) => String(d).includes('serving') && r()));
const loop = "$o='"+samples+"'; $s='"+stop+"'; $prev=@{}; while (-not (Test-Path $s)) { $t=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds(); $ps=Get-Process; $tot=0.0; $n=0; $ws=0; $pm=0; $top=''; $topd=0.0; foreach ($p in $ps) { $c=$p.TotalProcessorTime.TotalSeconds; if ($p.Path -like '*ms-playwright*') { $tot+=$c; $n++; $ws+=$p.WorkingSet64; $pm+=$p.PagedMemorySize64 } elseif ($prev.ContainsKey($p.Id)) { $d=$c-$prev[$p.Id]; if ($d -gt $topd) { $topd=$d; $top=$p.Name } }; $prev[$p.Id]=$c }; $os=Get-CimInstance Win32_OperatingSystem; \"$t $([math]::Round($tot,2)) $n $([math]::Round($ws/1MB)) $([math]::Round($pm/1MB)) $([math]::Round($os.FreePhysicalMemory/1KB)) $([math]::Round($os.FreeVirtualMemory/1KB)) $top $([math]::Round($topd,2))\" | Out-File -Append -Encoding ascii $o; Start-Sleep -Milliseconds 500 }";
const sampler = spawn("powershell.exe", ["-NoProfile", "-Command", loop], { stdio: "inherit" });
await new Promise((r) => setTimeout(r, 3000));
const browser = await (which === 'webkit' ? webkit : chromium).launch();
const page = await browser.newPage();
mark('launched');
await new Promise((r) => setTimeout(r, 5000));
mark('start');
await page.goto('http://127.0.0.1:8792/runtime/web/index.html?session=aube-1645');
await page.waitForFunction(() => window.formicariumResult !== undefined, null, { timeout: 600000 });
const r = await page.evaluate(() => window.formicariumResult);
mark(`done steps=${r.steps.map((s) => (s.elapsedMs / 1000).toFixed(1)).join(',')}`);
await new Promise((res) => setTimeout(res, 20000));
mark('closing');
await page.close(); await browser.close();
await new Promise((res) => setTimeout(res, 3000));
writeFileSync(stop, '');
await new Promise((res) => setTimeout(res, 2000));
server.kill();
console.log(`steps=${r.steps.map((s) => (s.elapsedMs / 1000).toFixed(1)).join(',')} exit=${r.exitCode}`);
